### PR TITLE
Now playing message

### PR DESCRIPTION
**Pull request by pryzmian**
feat(music): implement Song Announce Feature

- Extend `metadata` property in `ExtendedGuildQueuePlayerNode` type to include `lastMessage` property.
- Enable music bot to announce the start of a new song by sending a message to the channel.
- Add new event, `playerFinish`, to fetch and delete the last song-announce message if possible.
- Modify `play` command to accommodate these changes.

### CODE REVIEW

**Review by mariusbegby — CHANGES_REQUESTED** [review]
Carries over same changes as PR https://github.com/mariusbegby/cadence-discord-bot/pull/343

You need to sync your main branch in fork to match Cadence repo main branch. Then create new branch and only make desired changes.

**Comment by pryzmian** [comment]
> Carries over same changes as PR https://github.com/mariusbegby/cadence-discord-bot/pull/343
> 
> 
> 
> You need to sync your main branch in fork to match Cadence repo main branch. Then create new branch and only make desired changes.

That's what I did, but I don't know what the changes made in the previous pr synced with this new branch

**Comment by mariusbegby** [comment]
@pryzmian Because last PR your changes was on main branch. So this time, when you create a new branch off of your main branch, those changes carried over to your new branch.

You need to somehow make your main branch be in sync with cadence. Now it's not:
image

Easiest would be to delete and recreate fork I think. Or pull latest changes from cadence and delete/revert your previous commits to main branch.

**Comment by pryzmian** [comment]
I'll delete the fork and code everything again, also, is it okay if I leave the changes from the play command or i should leave it the way you coded it first?

**Comment by mariusbegby** [comment]
> I'll delete the fork and code everything again, also, is it okay if I leave the changes from the play command or i should leave it the way you coded it first?

Is there a benefit to the changes?

**Comment by pryzmian** [comment]
> > I'll delete the fork and code everything again, also, is it okay if I leave the changes from the play command or i should leave it the way you coded it first?
> 
> 
> 
> Is there a benefit to the changes? 
No lol, I'll just make the song-announce feature and that's it, I can also try and make a song-request-channel with player controls using buttons if you want

**Pull request closed without merging**
