### PR TITLE
Fixing Docker Build Errors

### PR DESCRIPTION
**Pull request by missfrizzy**
These changes correct a few issues that arise during the Docker container build process. 

## Changes
- adds missing locales and prisma copy to the Dockerfile
- adds missing type of `any` for the error return in guildDatabaseClient
- sets the typescript compiler option `noImplicitAny` to false

### CODE REVIEW

**Comment by missfrizzy** [comment]
*fingers crossed no CI issues*

**Review by mariusbegby — APPROVED** [review]
lgtm

prisma changes are sort of wip for persistent storage in v6, but these changes are appreciated so it's ready :)

**Comment by mariusbegby** [comment]
@missfrizzy fyi I have now updated the Dockerfile and also added a `canary` tag which builds on each push to `main` branch, so it has latest updates.

Let me know if any issues arise with this new Dockerfile.

**Comment by missfrizzy** [comment]
@mariusbegby oh okay! I'll sync up and give it a try tomorrow. Just encountered a weird error with youtube-ext not being able to process youtube stream returns so hopefully that's not happening in main too.

**Comment by mariusbegby** [comment]
It's happening in main and all versions of cadence using `youtube-ext`, the issue is in the dependency not handling YouTube HTTP 302 Found response. Seems YouTube updated their systems and what response codes they send out, which `youtube-ext` has never handled, causing sudden issues.

**Temporary fix:**
- Use `npm install @distube/ytdl-core --save`, `npm remove youtube-ext --save` (changes dependency for youtube extraction)
- Remove ipRotationConfig from `createPlayer.ts` completely, like so:

```ts
const player: Player = new Player(client, {
    useLegacyFFmpeg: false,
    skipFFmpeg: false,
    ytdlOptions: {
        quality: 'highestaudio',
        highWaterMark: 1 << 25,
        // no ipRotationConfig here
        requestOptions: {
            headers: {
                cookie: process.env.YT_COOKIE || ''
            }
        }
    }
});
```

Then `npm run build` and restart.

**Comment by missfrizzy** [comment]
@mariusbegby ahhh yup that was it, that was also the same fix I came up with myself that night hahaha.

The new Dockerfile looks like it's running well! No issues running it so far

**Pull request merged**
