### PR TITLE
Autoleave

### PR DESCRIPTION
**Pull request by TakenMC**
## Changes
Added auto leave for when the bot is alone in vc.

### Dependencies
N/A

### CODE REVIEW

**Comment by mariusbegby** [comment]
Hi @TakenMC, thanks for the PR. This should already be implemented through `discord-player`. There is a config option available to adjust this to your needs: https://github.com/mariusbegby/cadence-discord-bot/blob/main/config/default.js#L126
See `leaveOnEmpty` and `leaveOnEmptyCooldown` props. By default should leave on empty channel after 10 minutes.

The options are applied when creating queue object, such as seen here: https://github.com/mariusbegby/cadence-discord-bot/blob/main/src/interactions/commands/player/play.ts#L112

You can read more about this here in discord-player docs: https://discord-player.js.org/docs/discord-player/type/GuildNodeInit

If there are issues getting this to work let me know and we can look into a bug fix.

**Comment by TakenMC** [comment]
Not sure if I just check to early but I feel like it never leaves tho I'll see if it's broken or not then I'll update you on this

**Comment by mariusbegby** [comment]
@TakenMC honestly I haven't tested in a long time. Might have been broken after updating dependencies, since this functionality belongs to a dependency (`discord-player`).

If it doesn't work, please let me know. If so, we can either:
- Hook into discord-player event and override its logic (I think an event is emitted during this leaveOnEmpty state)
- Disable `discord-player` functionality around this and implement your solution into the codebase

Just get back here when you've tested :)

**Comment by TakenMC** [comment]
It seems to work fine I am sorry for the inconvenience as I would see it still lingering in voice chats and thought it didn't auto leave.

Tho could you make the time maybe 5 mins

**Comment by mariusbegby** [comment]
@TakenMC you can override the default config locally, create a file `/config/local.js`. Just copy over exactly the settings you want to change, and it will override.

So you can put in `/config/local.js` this:
```js
module.exports.playerOptions = {
    leaveOnEmpty: true,
    leaveOnEmptyCooldown: 0, // this is in milliseconds, so 1000 = 1 second
};
```

You don't need to copy over any other settings or even properties on this setting, unless you want to override more settings.

Setting it to 0 cooldown should make it leave instantly. By using the config people can set different values. For now I think we should keep all cooldown values to 10 minutes since it's been like that for a long time. People self-hosting the bot can always adjust the config as stated to adjust this to their needs.

Let me know if you have any problems with the configuration or around this functionality. I'll go ahead and close this PR for now, since you confirmed it should work, but don't hesitate to comment here or in the support server if have questions or want to discuss anything :)

**Pull request closed without merging**
